name: Android Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Up JDK
        uses: actions/setup/java@v1
        with:
          java:
            java-version: 19
      - name: Run Android Tests
        run: ./gradlew connectedAndroidTest

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble